import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import {ReactNode, Suspense} from 'react';
import {AppProviders} from '@/shared/providers/AppProviders';
import Header from '@/shared/ui/Header/Header';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin', 'cyrillic'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className={`${roboto.variable} antialiased`} suppressHydrationWarning>
            <body className="min-h-screen bg-background text-foreground flex flex-col">
                <AppProviders>
                    <Suspense fallback={null}>
                        <Header/>
                    </Suspense>
                    <main className="container mx-auto p-6 w-full flex-1">
                        {children}
                    </main>
                </AppProviders>
            </body>
        </html>
    );
}
