import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import '@/shared/styles/globals.css';
import {ReactNode} from 'react';
import {AppProviders} from '@/shared/providers/AppProviders';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin', 'cyrillic'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className={`${roboto.variable} antialiased`}>
            <body>
                <AppProviders>
                    {children}
                </AppProviders>
            </body>
        </html>
    );
}
